baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "carinthia"

[params.social]
  github = "vlow"
  linkedin = "flo"
  mastodon = "mastodon"
  pixelfed = "pixelfed"
  peertube = "peertube"
  rss = true

[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10

    [[menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 20

    [[menus.main]]
        name = 'Tags'
        pageRef = '/tags'
        weight = 30

[module]
    [module.hugoVersion]
        extended = false
        min = '0.146.0'
