baseURL = 'https://tc3.eu/'
languageCode = 'en-us'
title = 'tc3'
theme = "carinthia"

[params]
  subtitle = "Thoughts on Software Engineering and Management"

[params.social]
  github = "vlow"
  linkedin = "flo"
  mastodon = "mastodon"
  pixelfed = "pixelfed"
  peertube = "peertube"
  rss = true

[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10

    [[menus.main]]
        name = 'Blips'
        pageRef = '/blips'
        weight = 20

    [[menus.main]]
        name = 'Articles'
        pageRef = '/posts'
        weight = 30

    [[menus.main]]
        name = 'Projects'
        pageRef = '/projects'
        weight = 40

    [[menus.main]]
        name = 'Library'
        pageRef = '/library'
        weight = 50

    [[menus.main]]
        name = 'Tags'
        pageRef = '/tags'
        weight = 60

[module]
    [module.hugoVersion]
        extended = false
        min = '0.146.0'

[markup]
  [markup.highlight]
    noClasses = false
    style = "none"
    lineNos = false

