baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "carinthia"

[params.social]
  github = "vlow"
  linkedin = "flo"
  mastodon = "mastodon"
  pixelfed = "pixelfed"
  peertube = "peertube"
