baseURL = "http://localhost:1314"
languageCode = "en-us"
title = "Carinthia Theme Test"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menus.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menus.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
